# ----------------------------------------------------------------------
# RHS Computer Science - CS1 Configuration
# ----------------------------------------------------------------------

# Site Settings
title: CS1
description: >-
  Code. Create. Contribute. Empowering RHS Eagles to master the code, 
  create innovative solutions, and contribute to the future of technology.
author: RHS Computer Science

# Theme Settings
theme: jekyll-theme-cayman

# GitHub Settings (Helps the theme generate the "View on GitHub" buttons)
repository: mr-poston/CS1

# Build Settings (Excludes unnecessary files from being published)
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfile
  - gemfile.lock
  - node_modules/
  - vendor/
